- include: pkg-CentOs.yml
  when: ( "{{ nginx_install_method }}" == "package"
        and "{{ ansible_os_family }}"  == "RedHat")

- include: pkg-Debian.yml
  when: ( "{{ nginx_install_method }}" == "package"
        and "{{ ansible_distribution }}" == "Ubuntu"
        or "{{ ansible_distribution }}" == "Debian")

- include: configure.yml

- include: default_site.yml

- include: sites.yml

- include: firewalld.yml
  when: ("{{ nginx_enable_ports }}" and "{{ ansible_service_mgr }}" == "systemd")
