- name: Setting right values for Red Hat systems
  set_fact:
    nginx_user: nginx
    nginx_group: nginx

- name: Nginx | Add the nginx repository
  yum_repository:
    description: nginx
    name: nginx
    baseurl: 'http://nginx.org/packages/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/'
    enabled: yes
    gpgcheck: no
    state: present

- name: Nginx | Make sure nginx is installed (package)
  yum:
    name: nginx
    state: present
    update_cache: yes
  notify:
    - restart nginx

- name: Nginx | Enable nginx service
  service:
    name: nginx
    enabled: yes
  when: "{{ nginx_service_enable }}"

- include: directories.yml
