- name: Nginx | Update the configurations for normal sites inventory
  template:
    src: site.j2
    dest: "{{ nginx_dir }}/sites-available/{{ item.site.name }}"
  with_items: "{{ nginx_sites }}"
  when: nginx_sites is defined
        and "{{ item.site.custom_config }}" == "False"

- name: Nginx | Update the configurations for cusrom sites inventory
  copy:
    src: "{{ item.site.custom_config_path }}"
    dest: "{{ nginx_dir }}/sites-available/{{ item.site.name }}"
  with_items: "{{ nginx_sites }}"
  when: nginx_sites is defined
        and "{{ item.site.custom_config }}" == "True"
        and "{{ item.site.custom_config_path }}" is defined
  ignore_errors: True

- name: Nginx | Create virtual sites directories
  file:
    path: "{{ nginx_www_dir }}/{{ item.site.name }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755
  with_items: "{{ nginx_sites }}"
  when: nginx_sites is defined 
        and "{{ item.site.do_not_create_dir | default(False) }}" != "True"

- name: Nginx | Enable sites
  file:
    path: "{{ nginx_dir }}/sites-enabled/{{ item.site.name }}"
    src: "{{ nginx_dir }}/sites-available/{{ item.site.name }}"
    state: link
  with_items: "{{ nginx_sites }}"
  notify:
    - reload nginx
  when: nginx_sites is defined
        and "{{ item.site.enabled }}" == "True"

- name: Nginx | Disable sites
  file:
    path: "{{ nginx_dir }}/sites-enabled/{{ item.site.name }}"
    state: absent
  with_items: "{{ nginx_sites }}"
  notify:
    - reload nginx
  when: nginx_sites is defined
        and "{{ item.site.enabled }}" == "False"
